import 'dart:ui';

class AppColors {
  static const textColorWhite = Color(0xffFFFFFF);
  static const textColorBlack = Color(0xff000000);
  static const whiteColorWithOpacity = Color(0xffFFFFFF);
  static const backgroundColor = Color(0xff262626);
  static const gradientColor1 = Color(0xff92B928);
  static const gradientColor2 = Color(0xffC9C317);
  static const gradientColor3 = Color(0xff191C1F);
  static const textColorGrey = Color(0xff6B6F72);
  static const textColorGreen = Color(0xff20BF6B);
  static const textClrGreyIconsContainerSecurity = Color(0xffD9D9D9);
  static const footerColor = Color(0xff6B6F72);
  static const whiteShade = Color(0xffF2F2F2);
  static const blackColour = Color(0xff191C1F);
  static const errorColor = Color(0xffFA0848);
  static const paymentFailedDialog = Color(0xffFA0848);
  static const textColorGreyShade2 = Color(
    0xffB3B7BB,
  );
  static const textColorGreyShade3 = Color(0xff585B5F);
  static const activeButtonColor = Color(0xff66D71B);
  static const hexaGreen = Color(0xff66D71B);
  static const passwordGreen = Color(0xff06F678);
  static const selectedLanguageBorder = Color(0xff66D71B);
  static const selectedCardAndBankBorder = Color(0xff66D71B);
  static const textColorToska = Color(0xff00FFF6);
  static const dotContainerColorGreen = Color(0xff06F678);
  static const transparentBtnBorderColorDark = Color(0xff7F7F7F);
  static const inActiveDialogButton = Color(0xff7F7F7F);
  static const appSecondButton = Color(0xff7F7F7F);
  static const transparentBtnBorderColorLight = Color(0xffB3B7BB);
  static const bluishClr = Color(0xff12D0DB);
  static const emailNotVerifiedContainer = Color(0xFA08481A);
  static const disabaledBtnColor = Color(0xffCFD1D4);
  static const drawerDividerdarkColor = Color(0xff424242);
  static const drawerDividerlightColor = Color(0xffB3B7BB);
  static const emailSecurityVerified = Color(0xffDADADA);
  static const tabColorlightMode = Color(0xff7F7F7F);
  static const deleteAccWarningClr = Color(0xff7F7F7F);
  static const avatarColor = Color(0xff6B6F72);
  static const activityPriceredClr = Color(0xffEE0505);
  static const activityPricegreenClr = Color(0xff04BD16);
  static const tagFillClrDark = Color(0xff333333);
  static const drawerOptBackgroundClr = Color(0xff333333);
  static const tagFillClrLight = Color(0xffB3B7BB);
  static const activityDividerClrDark = Color(0xff424242);
  static const activityDividerClrLight = Color(0xffB3B7BB);
  static const tabUnselectedClorLight = Color(0xff7F7F7F);
  static const profileHeaderDark = Color(0xff2B2B2B);
  static const textFieldParentDark = Color(0xff2B2B2B);
  static const connectedSitesPopupsClr = Color(0xff2B2B2B);
  static const showDialogClr = Color(0xff2B2B2B);
  static const connectedSitesDialog = Color(0xff2B2B2B);
  static const appButtonUnselectedDark = Color(0xff2B2B2B);
  static const transactionFeeContainer = Color(0xff343434);
  static const transactionSummNeoBorder = Color(0xff343535);
  static const connectDiscSites = Color(0xff04A20A);
  static const paymentTypesBorder = Color(0x3A3C3C);
  static const transactionFeeBorder = Color(0xff3A3C3C);
  static const accountAtRisk = Color(0xffFECACA);
  static const verifyAccount = Color(0xffDC2626);
  static const languageDivider = Color(0xff343535);
  static const transactionReqBorderWhole= Color(0xff2D2D2D);
  static const headerSubTitle= Color(0xff93979B);
  static const nftsSubtitle= Color(0xff93979B);
}
